"= assignment operator"
"+ concatenation"
"+ addition"
"- subtraction"
"* multiplication"
"// floor division"
"/ division"
"% modulus"
"* * exponent"
"== equals"
"# comment"
'single quotes'
"double quotes"
